-- Room_types: add all ERD fields
ALTER TABLE room_types
    ADD COLUMN IF NOT EXISTS gallery_images TEXT,
    ADD COLUMN IF NOT EXISTS min_area DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS max_area DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS max_pets INTEGER,
    ADD COLUMN IF NOT EXISTS min_pet_weight DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS max_pet_weight DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS suitable_pet_sizes VARCHAR(500),
    ADD COLUMN IF NOT EXISTS suitable_pet_types TEXT,
    ADD COLUMN IF NOT EXISTS standard_amenities TEXT,
    ADD COLUMN IF NOT EXISTS features TEXT,
    ADD COLUMN IF NOT EXISTS cancellation_policy TEXT,
    ADD COLUMN IF NOT EXISTS requires_vaccination BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS requires_health_check BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS meta_title VARCHAR(150),
    ADD COLUMN IF NOT EXISTS meta_description VARCHAR(255),
    ADD COLUMN IF NOT EXISTS keywords TEXT;

-- Rooms: add all ERD fields; building length per ERD VARCHAR(20)
ALTER TABLE rooms
    ADD COLUMN IF NOT EXISTS location_note VARCHAR(500),
    ADD COLUMN IF NOT EXISTS custom_price_per_night DECIMAL(12,2),
    ADD COLUMN IF NOT EXISTS price_note VARCHAR(500),
    ADD COLUMN IF NOT EXISTS additional_amenities TEXT,
    ADD COLUMN IF NOT EXISTS removed_amenities TEXT,
    ADD COLUMN IF NOT EXISTS images TEXT,
    ADD COLUMN IF NOT EXISTS capacity INTEGER,
    ADD COLUMN IF NOT EXISTS expected_checkout_date DATE,
    ADD COLUMN IF NOT EXISTS current_check_in_date DATE,
    ADD COLUMN IF NOT EXISTS last_cleaned_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS last_maintenance_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS maintenance_notes TEXT,
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS internal_notes TEXT,
    ADD COLUMN IF NOT EXISTS area DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS block_reason TEXT,
    ADD COLUMN IF NOT EXISTS blocked_from TIMESTAMP,
    ADD COLUMN IF NOT EXISTS blocked_to TIMESTAMP,
    ADD COLUMN IF NOT EXISTS blocked_by VARCHAR(255);
