-- === Merged from: V13__add_skill_id_to_services.sql ===
-- ThÃªm cá»™t skill_id vÃ o báº£ng services
ALTER TABLE services ADD COLUMN IF NOT EXISTS skill_id BIGINT;

-- Táº¡o khÃ³a ngoáº¡i
DO $$ 
BEGIN 
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_services_skills'
    ) THEN
        ALTER TABLE services ADD CONSTRAINT fk_services_skills FOREIGN KEY (skill_id) REFERENCES skills(skill_id);
    END IF;
END $$;


-- === Merged from: V13__shift_role_config_and_registration_role_work_type.sql ===
-- Báº£ng Ä‘á»‹nh má»©c sá»‘ lÆ°á»£ng theo vai trÃ² cho tá»«ng ca (shift_id, position_id, max_slots)
create table if not exists shift_role_configs (
    config_id bigint generated by default as identity,
    work_shift_id bigint not null,
    position_id bigint not null,
    max_slots integer not null default 1,
    is_active boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (config_id),
    constraint uk_shift_role_config_shift_position unique (work_shift_id, position_id),
    constraint fk_shift_role_config_work_shift foreign key (work_shift_id) references work_shifts(shift_id),
    constraint fk_shift_role_config_position foreign key (position_id) references staff_positions(position_id)
);

-- Bá»• sung role_at_registration (position_id) vÃ  work_type cho Ä‘Äƒng kÃ½ ca
alter table work_shift_registrations
    add column if not exists position_id bigint,
    add column if not exists work_type varchar(20);

-- Chá»‰ thÃªm constraint náº¿u chÆ°a tá»“n táº¡i (DB Ä‘Ã£ Ã¡p dá»¥ng V4 cÅ© cÃ³ thá»ƒ Ä‘Ã£ cÃ³)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_registration_position'
      AND conrelid = 'public.work_shift_registrations'::regclass
  ) THEN
    ALTER TABLE work_shift_registrations
      ADD CONSTRAINT fk_registration_position
      FOREIGN KEY (position_id) REFERENCES staff_positions(position_id);
  END IF;
END $$;



