-- V18: Ensure staff_fixed_schedules table exists (idempotent).
-- Some environments may have Flyway history but missing table; this migration recreates it safely.

CREATE TABLE IF NOT EXISTS staff_fixed_schedules (
    schedule_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id      BIGINT NOT NULL,
    position_id   BIGINT NOT NULL,
    day_of_week   INTEGER NOT NULL,
    is_afternoon  BOOLEAN NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255)
);

-- Unique constraint (ignore if already exists)
DO $$
BEGIN
    ALTER TABLE staff_fixed_schedules
        ADD CONSTRAINT uk_staff_fixed_schedule_staff_position_day_slot
            UNIQUE (staff_id, position_id, day_of_week, is_afternoon);
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Foreign keys (ignore if already exist)
DO $$
BEGIN
    ALTER TABLE staff_fixed_schedules
        ADD CONSTRAINT fk_staff_fixed_schedule_staff
            FOREIGN KEY (staff_id) REFERENCES staff_profiles(staff_id);
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE staff_fixed_schedules
        ADD CONSTRAINT fk_staff_fixed_schedule_position
            FOREIGN KEY (position_id) REFERENCES staff_positions(position_id);
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

