
    create table app_settings (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        created_by varchar(255),
        description varchar(255),
        setting_key varchar(255) not null unique,
        setting_value TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table avatar_images (
        is_active boolean not null,
        is_deleted boolean not null,
        is_predefined boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        category varchar(100),
        image_url varchar(500) not null,
        alt_text varchar(255),
        created_by varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table blog_categories (
        display_order integer,
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        parent_id bigint,
        updated_at timestamp(6) not null,
        name varchar(100) not null,
        description varchar(500),
        alt_image varchar(255),
        created_by varchar(255),
        image_url varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table blog_post_tags (
        blog_post_id bigint not null,
        blog_tag_id bigint not null
    );

    create table blog_posts (
        display_order integer,
        is_active boolean not null,
        is_deleted boolean not null,
        view_count integer not null,
        category_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        parent_id bigint,
        updated_at timestamp(6) not null,
        status varchar(50) not null check (status in ('DRAFT','PUBLISHED','ARCHIVED')),
        title varchar(200) not null,
        excerpt varchar(500),
        featured_image varchar(500),
        meta_description varchar(500),
        alt_image varchar(255),
        content TEXT,
        created_by varchar(255),
        meta_title varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table blog_tags (
        display_order integer,
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        name varchar(100) not null unique,
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table booking_pet_services (
        check_in_date date,
        check_out_date date,
        customer_rating integer,
        is_active boolean not null,
        is_deleted boolean not null,
        number_of_nights integer,
        subtotal numeric(12,2),
        unit_price numeric(12,2),
        actual_end_time timestamp(6),
        actual_start_time timestamp(6),
        assigned_staff_id bigint,
        booking_pet_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        room_id bigint,
        scheduled_end_time timestamp(6),
        scheduled_start_time timestamp(6),
        service_combo_id bigint,
        service_id bigint,
        time_slot_id bigint,
        updated_at timestamp(6) not null,
        status varchar(50),
        after_photos TEXT,
        before_photos TEXT,
        created_by varchar(255),
        customer_review TEXT,
        during_photos TEXT,
        staff_notes TEXT,
        updated_by varchar(255),
        videos TEXT,
        primary key (id)
    );

    create table booking_pets (
        is_active boolean not null,
        is_deleted boolean not null,
        weight_at_booking numeric(6,2),
        booking_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        pet_profile_id bigint,
        updated_at timestamp(6) not null,
        emergency_contact_phone varchar(20),
        arrival_condition TEXT,
        arrival_photos TEXT,
        belonging_photos TEXT,
        created_by varchar(255),
        departure_condition TEXT,
        departure_photos TEXT,
        emergency_contact_name varchar(255),
        feeding_instructions TEXT,
        food_brand TEXT,
        food_brought TEXT,
        health_issues TEXT,
        pet_condition_notes TEXT,
        pet_name varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table bookings (
        deposit numeric(12,2),
        is_active boolean not null,
        is_deleted boolean not null,
        paid_amount numeric(12,2),
        refund_amount numeric(12,2),
        remaining_amount numeric(12,2),
        total_amount numeric(12,2),
        booking_end_date timestamp(6),
        booking_start_date timestamp(6),
        cancelled_at timestamp(6),
        confirm_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id uuid,
        customer_phone varchar(20),
        booking_code varchar(50) not null unique,
        booking_type varchar(50),
        payment_method varchar(50),
        payment_status varchar(50),
        refund_method varchar(50),
        status varchar(50),
        cancelled_by varchar(100),
        confirm_by varchar(100),
        source varchar(100),
        created_by varchar(255),
        customer_email varchar(255),
        customer_name varchar(255),
        internal_notes TEXT,
        note TEXT,
        special_requests TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table feedbacks (
        is_active boolean not null,
        is_deleted boolean not null,
        is_edited boolean not null,
        is_purchased boolean not null,
        rating integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        variant_id bigint,
        order_id uuid,
        user_id uuid,
        comment TEXT,
        created_by varchar(255),
        guest_email varchar(255),
        guest_name varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table order_items (
        is_active boolean not null,
        is_deleted boolean not null,
        quantity integer not null,
        total_price numeric(10,2) not null,
        unit_price numeric(10,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint,
        updated_at timestamp(6) not null,
        variant_id bigint,
        order_id uuid not null,
        sku varchar(50),
        variant_name varchar(100),
        product_name varchar(200) not null,
        image_url varchar(500),
        alt_image varchar(255),
        created_by varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table orders (
        discount_amount numeric(10,2) not null,
        final_amount numeric(10,2) not null,
        is_active boolean not null,
        is_deleted boolean not null,
        latitude float(53),
        longitude float(53),
        shipping_fee numeric(10,2) not null,
        subtotal numeric(10,2) not null,
        cancelled_at timestamp(6),
        completed_at timestamp(6),
        created_at timestamp(6) not null,
        delivered_at timestamp(6),
        delivering_at timestamp(6),
        return_requested_at timestamp(6),
        updated_at timestamp(6) not null,
        user_address_id bigint,
        id uuid not null,
        promotion_id uuid,
        user_id uuid,
        order_type varchar(20) not null check (order_type in ('ONLINE','OFFLINE')),
        shipping_phone varchar(20) not null,
        status varchar(20) not null check (status in ('PENDING','CONFIRMED','PROCESSING','DELIVERING','DELIVERED','COMPLETED','CANCELLED','RETURN_REQUESTED','RETURNED')),
        order_code varchar(50) not null unique,
        voucher_code varchar(50),
        cancelled_by varchar(100),
        shipping_name varchar(100) not null,
        admin_return_note TEXT,
        cancel_reason TEXT,
        created_by varchar(255),
        guest_email varchar(255),
        notes TEXT,
        return_evidence TEXT,
        return_reason TEXT,
        shipping_address TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table payments (
        amount numeric(10,2) not null,
        is_active boolean not null,
        is_deleted boolean not null,
        completed_at timestamp(6) with time zone,
        created_at timestamp(6) not null,
        failed_at timestamp(6) with time zone,
        updated_at timestamp(6) not null,
        version bigint,
        id uuid not null,
        order_id uuid not null,
        payment_gateway varchar(50),
        payment_method varchar(50) not null check (payment_method in ('CASH','BANK_TRANSFER','CREDIT_CARD','E_WALLET')),
        status varchar(50) not null check (status in ('PENDING','PROCESSING','COMPLETED','FAILED','VOIDED','REFUND_PENDING','REFUNDED')),
        transaction_id varchar(100),
        created_by varchar(255),
        notes TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table permissions (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        module varchar(50) not null,
        name varchar(100) not null unique,
        created_by varchar(255),
        description varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table pet_profiles (
        birth_date date,
        is_active boolean not null,
        is_deleted boolean not null,
        is_neutered boolean,
        weight numeric(5,2),
        avatar_image_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id uuid not null,
        gender varchar(20) check (gender in ('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY')),
        pet_type varchar(50) not null check (pet_type in ('DOG','CAT','OTHER')),
        breed varchar(100),
        name varchar(100) not null,
        avatar_url varchar(500),
        alt_image varchar(255),
        created_by varchar(255),
        health_note TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table product_age_range (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        name varchar(50) not null unique,
        created_by varchar(255),
        description varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table product_age_ranges (
        age_range_id bigint not null,
        product_id bigint not null
    );

    create table product_attribute_supported_units (
        attribute_id bigint not null,
        unit varchar(255) not null check (unit in ('PIECE','BOX','PACK','BAG','BOTTLE','CAN','SET','COMBO','KG','GRAM','LITER','ML','MM','CM','M'))
    );

    create table product_attribute_values (
        amount numeric(10,2),
        display_order integer not null,
        is_active boolean not null,
        is_deleted boolean not null,
        attribute_id bigint not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        value_id bigint generated by default as identity,
        unit varchar(20) check (unit in ('PIECE','BOX','PACK','BAG','BOTTLE','CAN','SET','COMBO','KG','GRAM','LITER','ML','MM','CM','M')),
        display_code varchar(50),
        created_by varchar(255),
        updated_by varchar(255),
        value varchar(255) not null,
        primary key (value_id)
    );

    create table product_attributes (
        display_order integer not null,
        is_active boolean not null,
        is_deleted boolean not null,
        attribute_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        display_type varchar(50) not null check (display_type in ('TEXT','SELECT','CHECKBOX','RADIO','MULTI_SELECT','COLOR')),
        name varchar(100) not null,
        created_by varchar(255),
        updated_by varchar(255),
        primary key (attribute_id)
    );

    create table product_brands (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        name varchar(100) not null unique,
        description varchar(500),
        alt_image varchar(255),
        created_by varchar(255),
        logo_url varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        website_url varchar(255),
        primary key (id)
    );

    create table product_categories (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        parent_id bigint,
        updated_at timestamp(6) not null,
        name varchar(100) not null,
        description varchar(500),
        alt_image varchar(255),
        created_by varchar(255),
        image_url varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table product_images (
        display_order integer not null,
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        image_url varchar(500) not null,
        alt_text varchar(255),
        created_by varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table product_pet_types (
        product_id bigint not null,
        pet_type varchar(50) not null check (pet_type in ('DOG','CAT','OTHER'))
    );

    create table product_product_attributes (
        attribute_id bigint not null,
        product_id bigint not null
    );

    create table product_product_categories (
        product_category_id bigint not null,
        product_id bigint not null
    );

    create table product_product_tags (
        product_id bigint not null,
        product_tag_id bigint not null
    );

    create table product_tags (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        color varchar(20),
        name varchar(50) not null unique,
        slug varchar(100) not null unique,
        created_by varchar(255),
        description TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table product_variant_attribute_values (
        value_id bigint not null,
        variant_id bigint not null
    );

    create table product_variants (
        height integer,
        is_active boolean not null,
        is_deleted boolean not null,
        length integer,
        price numeric(10,2) not null,
        sale_price numeric(10,2),
        stock_quantity integer not null,
        weight integer not null,
        width integer,
        created_at timestamp(6) not null,
        featured_image_id bigint,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        variant_id bigint generated by default as identity,
        sku varchar(50) not null unique,
        status varchar(50) not null check (status in ('DRAFT','ACTIVE','HIDDEN')),
        unit varchar(50) not null check (unit in ('PIECE','BOX','PACK','BAG','BOTTLE','CAN','SET','COMBO','KG','GRAM','LITER','ML','MM','CM','M')),
        name varchar(100) not null,
        created_by varchar(255),
        updated_by varchar(255),
        primary key (variant_id)
    );

    create table products (
        is_active boolean not null,
        is_deleted boolean not null,
        max_price numeric(10,2),
        min_price numeric(10,2),
        sold_count integer not null,
        view_count integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_brand_id bigint,
        updated_at timestamp(6) not null,
        barcode varchar(50) unique,
        product_type varchar(50) not null check (product_type in ('SIMPLE','VARIABLE')),
        sku varchar(50) unique,
        status varchar(50) not null check (status in ('DRAFT','ACTIVE','HIDDEN')),
        stock_status varchar(50) not null check (stock_status in ('IN_STOCK','OUT_OF_STOCK','LOW_STOCK')),
        material varchar(100),
        origin varchar(100),
        name varchar(200) not null,
        meta_description varchar(500),
        created_by varchar(255),
        description TEXT,
        meta_title varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table promotion_apply_categories (
        category_id bigint,
        promotion_id uuid not null
    );

    create table promotion_apply_products (
        product_id bigint,
        promotion_id uuid not null
    );

    create table promotion_usages (
        is_active boolean not null,
        is_deleted boolean not null,
        usage_count integer not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        id uuid not null,
        promotion_id uuid not null,
        user_id uuid not null,
        created_by varchar(255),
        updated_by varchar(255),
        primary key (id),
        unique (user_id, promotion_id)
    );

    create table promotions (
        discount_value numeric(10,2) not null,
        is_active boolean not null,
        is_deleted boolean not null,
        max_discount_amount numeric(10,2),
        min_order_amount numeric(10,2),
        usage_count integer not null,
        usage_limit integer,
        usage_limit_per_user integer,
        created_at timestamp(6) not null,
        end_date timestamp(6) not null,
        start_date timestamp(6) not null,
        updated_at timestamp(6) not null,
        version bigint,
        id uuid not null,
        discount_type varchar(20) not null check (discount_type in ('PERCENTAGE','FIXED_AMOUNT')),
        scope varchar(20) not null check (scope in ('ALL','CATEGORY','PRODUCT','USER_SPECIFIC')),
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE','EXPIRED','SCHEDULED')),
        code varchar(50) not null unique,
        name varchar(200) not null,
        thumbnail varchar(500),
        alt_image varchar(255),
        created_by varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table ratings (
        is_active boolean not null,
        is_deleted boolean not null,
        is_verified_purchase boolean not null,
        rating_score numeric(2,1) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        user_id uuid not null,
        comment TEXT,
        created_by varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table role_permissions (
        permission_id bigint not null,
        role_id bigint not null,
        primary key (permission_id, role_id)
    );

    create table roles (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        name varchar(50) not null unique,
        created_by varchar(255),
        description varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table service_categories (
        display_order integer,
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        parent_id bigint,
        updated_at timestamp(6) not null,
        color_code varchar(20),
        pricing_model varchar(100),
        service_type varchar(100),
        meta_description varchar(500),
        category_name varchar(255) not null,
        created_by varchar(255),
        description TEXT,
        icon varchar(255),
        image_url varchar(255),
        meta_title varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table service_combo (
        combo_price numeric(12,2),
        discount_percentage numeric(5,2),
        display_order integer,
        is_active boolean not null,
        is_deleted boolean not null,
        is_popular boolean not null,
        max_pet_weight numeric(6,2),
        min_pet_weight numeric(6,2),
        original_price numeric(12,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        valid_from timestamp(6),
        valid_to timestamp(6),
        code varchar(50) not null unique,
        applicable_pet_types TEXT,
        combo_name varchar(255) not null,
        created_by varchar(255),
        description TEXT,
        img_url varchar(255),
        tags TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table service_combo_service (
        quantity integer not null,
        service_combo_id bigint not null,
        service_id bigint not null,
        primary key (service_combo_id, service_id)
    );

    create table service_pricing (
        holiday_multiplier numeric(5,2),
        is_active boolean not null,
        is_deleted boolean not null,
        max_weight numeric(6,2),
        min_weight numeric(6,2),
        peak_season_multiplier numeric(5,2),
        price numeric(12,2) not null,
        priority integer not null,
        weekend_multiplier numeric(5,2),
        created_at timestamp(6) not null,
        effective_from timestamp(6),
        effective_to timestamp(6),
        id bigint generated by default as identity,
        service_id bigint not null,
        updated_at timestamp(6) not null,
        created_by varchar(255),
        pricing_name varchar(255) not null,
        suitable_pet_types TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table services (
        advance_booking_hours integer,
        base_price numeric(12,2),
        buffer_time integer not null,
        cancellation_deadline_hours integer,
        display_order integer,
        duration integer not null,
        is_active boolean not null,
        is_addon boolean not null,
        is_critical boolean not null,
        is_deleted boolean not null,
        is_popular boolean not null,
        max_pets_per_session integer,
        required_staff_count integer,
        requires_vaccination boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        service_category_id bigint not null,
        updated_at timestamp(6) not null,
        addon_type varchar(50),
        code varchar(50) not null unique,
        price_unit varchar(50),
        meta_description varchar(500),
        short_description varchar(500),
        created_by varchar(255),
        description TEXT,
        gallery_images TEXT,
        image_url varchar(255),
        meta_title varchar(255),
        required_certifications TEXT,
        service_name varchar(255) not null,
        slug varchar(255) unique,
        suitable_pet_types TEXT,
        updated_by varchar(255),
        primary key (id)
    );

    create table shipping_rules (
        base_weight float(53),
        district_id integer,
        fee_per_km numeric(38,2),
        fixed_fee numeric(38,2),
        free_ship_distance_km float(53),
        free_ship_threshold numeric(38,2),
        is_active boolean not null,
        is_deleted boolean not null,
        is_inner_city boolean,
        is_self_ship boolean,
        max_internal_distance_km float(53),
        min_fee numeric(38,2),
        over_weight_fee numeric(38,2),
        province_id integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        created_by varchar(255),
        note varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table user_addresses (
        is_active boolean not null,
        is_default boolean,
        is_deleted boolean not null,
        latitude float(53),
        longitude float(53),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id uuid not null,
        address varchar(500) not null,
        created_by varchar(255),
        full_name varchar(255) not null,
        phone_number varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

    create table users (
        date_of_birth date,
        failed_login_attempts integer,
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        last_failed_login_at timestamp(6),
        locked_at timestamp(6),
        role_id bigint not null,
        updated_at timestamp(6) not null,
        id uuid not null,
        gender varchar(20) check (gender in ('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY')),
        avatar_url varchar(500),
        alt_image varchar(255),
        created_by varchar(255),
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255) not null,
        phone_number varchar(255),
        status varchar(255) not null check (status in ('ACTIVE','INACTIVE','LOCKED','PENDING_VERIFICATION')),
        updated_by varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    create table wishlists (
        is_active boolean not null,
        is_deleted boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        user_id uuid not null,
        created_by varchar(255),
        updated_by varchar(255),
        primary key (id),
        unique (user_id, product_id)
    );

    alter table if exists blog_categories 
       add constraint FK292v03312fj6oaespug7wubvu 
       foreign key (parent_id) 
       references blog_categories;

    alter table if exists blog_post_tags 
       add constraint FKlipo05x7bew7hgujgfbymqfns 
       foreign key (blog_tag_id) 
       references blog_tags;

    alter table if exists blog_post_tags 
       add constraint FK9lwi4pg2kl7ce7pa3r3yotb9w 
       foreign key (blog_post_id) 
       references blog_posts;

    alter table if exists blog_posts 
       add constraint FKob98yyhofb2qn7x1pk9nmo6aa 
       foreign key (category_id) 
       references blog_categories;

    alter table if exists blog_posts 
       add constraint FKii3kpc1rcixy82ujave63fexj 
       foreign key (parent_id) 
       references blog_posts;

    alter table if exists booking_pet_services 
       add constraint FKm9vqdradwnrmpqfk8wuecf8v2 
       foreign key (booking_pet_id) 
       references booking_pets;

    alter table if exists booking_pet_services 
       add constraint FKlrr1tpj5xog0s82d1kdw1u4un 
       foreign key (service_id) 
       references services;

    alter table if exists booking_pet_services 
       add constraint FK8krvdpj5q6ak6aiwoi1jwcbal 
       foreign key (service_combo_id) 
       references service_combo;

    alter table if exists booking_pets 
       add constraint FKtkcj62wcrpnvryqwkertht5dg 
       foreign key (booking_id) 
       references bookings;

    alter table if exists bookings 
       add constraint FKeyog2oic85xg7hsu2je2lx3s6 
       foreign key (user_id) 
       references users;

    alter table if exists feedbacks 
       add constraint FKti2ywtwc29ys1i591rmmaveyc 
       foreign key (product_id) 
       references products;

    alter table if exists feedbacks 
       add constraint FK312drfl5lquu37mu4trk8jkwx 
       foreign key (user_id) 
       references users;

    alter table if exists feedbacks 
       add constraint FKds69d22gp4wgx7rmm4jqqimr3 
       foreign key (variant_id) 
       references product_variants;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists order_items 
       add constraint FKemq71edpbn9wsxnxncfn1algp 
       foreign key (variant_id) 
       references product_variants;

    alter table if exists orders 
       add constraint FK42bki7v5u9s62olp5is82sd74 
       foreign key (promotion_id) 
       references promotions;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists orders 
       add constraint FKrx9ctot9t84fywnxf8931w6jq 
       foreign key (user_address_id) 
       references user_addresses;

    alter table if exists payments 
       add constraint FK81gagumt0r8y3rmudcgpbk42l 
       foreign key (order_id) 
       references orders;

    alter table if exists pet_profiles 
       add constraint FKrnb37ro3529er0sy919qnp3ty 
       foreign key (avatar_image_id) 
       references avatar_images;

    alter table if exists pet_profiles 
       add constraint FKmw3h9mxe6jdr5sdpacseolv4v 
       foreign key (user_id) 
       references users;

    alter table if exists product_age_ranges 
       add constraint FKr9uu2sm5ju6vjm0ipph0ev3xt 
       foreign key (age_range_id) 
       references product_age_range;

    alter table if exists product_age_ranges 
       add constraint FKrbs6qlvusmcc0b9ues032478w 
       foreign key (product_id) 
       references products;

    alter table if exists product_attribute_supported_units 
       add constraint FK7mu5nweum7563y1rlym0epgef 
       foreign key (attribute_id) 
       references product_attributes;

    alter table if exists product_attribute_values 
       add constraint FK1oveqdcusmrm22vlr6m0u2hnn 
       foreign key (attribute_id) 
       references product_attributes;

    alter table if exists product_categories 
       add constraint FKnhstaep8s818kydkq4teq8v4e 
       foreign key (parent_id) 
       references product_categories;

    alter table if exists product_images 
       add constraint FKqnq71xsohugpqwf3c9gxmsuy 
       foreign key (product_id) 
       references products;

    alter table if exists product_pet_types 
       add constraint FK4gw1y4isqol5e95sfhlgytbyd 
       foreign key (product_id) 
       references products;

    alter table if exists product_product_attributes 
       add constraint FKk62lardq7qa59pmx13e63cfdq 
       foreign key (attribute_id) 
       references product_attributes;

    alter table if exists product_product_attributes 
       add constraint FK93uiytk1wa4cftv558jc71tmw 
       foreign key (product_id) 
       references products;

    alter table if exists product_product_categories 
       add constraint FKt5ilgl3tb7ldicu0xcuqy13rr 
       foreign key (product_category_id) 
       references product_categories;

    alter table if exists product_product_categories 
       add constraint FK9o6pecoegi84yu5t75pkh3dqm 
       foreign key (product_id) 
       references products;

    alter table if exists product_product_tags 
       add constraint FKcskft8m780mim6qx6dc8xjrl5 
       foreign key (product_tag_id) 
       references product_tags;

    alter table if exists product_product_tags 
       add constraint FKcxdx37rb1w8q7xe7r1crsd90d 
       foreign key (product_id) 
       references products;

    alter table if exists product_variant_attribute_values 
       add constraint FKra7a6n0ure5aim9bmkjcaoc6t 
       foreign key (value_id) 
       references product_attribute_values;

    alter table if exists product_variant_attribute_values 
       add constraint FK2beos0oflybjy1nm7gfbfqlkg 
       foreign key (variant_id) 
       references product_variants;

    alter table if exists product_variants 
       add constraint FKkl69gg240nrmjyc9k0ys0m48w 
       foreign key (featured_image_id) 
       references product_images;

    alter table if exists product_variants 
       add constraint FKosqitn4s405cynmhb87lkvuau 
       foreign key (product_id) 
       references products;

    alter table if exists products 
       add constraint FKpvjh287e2rwiadduhvqv7rqwh 
       foreign key (product_brand_id) 
       references product_brands;

    alter table if exists promotion_apply_categories 
       add constraint FKtnkmkq3n7f2eb22gx9p3ohybn 
       foreign key (promotion_id) 
       references promotions;

    alter table if exists promotion_apply_products 
       add constraint FKf4d8fpv2ewm7ekxiif4u5l254 
       foreign key (promotion_id) 
       references promotions;

    alter table if exists promotion_usages 
       add constraint FKoyp72sti54877xp17yac81qai 
       foreign key (promotion_id) 
       references promotions;

    alter table if exists promotion_usages 
       add constraint FKufp8twapfql1y1tmdny6qetw 
       foreign key (user_id) 
       references users;

    alter table if exists ratings 
       add constraint FK228us4dg38ewge41gos8y761r 
       foreign key (product_id) 
       references products;

    alter table if exists ratings 
       add constraint FKb3354ee2xxvdrbyq9f42jdayd 
       foreign key (user_id) 
       references users;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists service_categories 
       add constraint FK1lggon6dtecbuwkkf706i1a15 
       foreign key (parent_id) 
       references service_categories;

    alter table if exists service_combo_service 
       add constraint FKig7c5886jtrtd990jjg9fm7n3 
       foreign key (service_id) 
       references services;

    alter table if exists service_combo_service 
       add constraint FKti91chdw3sw29vm6osbcdey0b 
       foreign key (service_combo_id) 
       references service_combo;

    alter table if exists service_pricing 
       add constraint FKorxagb45t4ut61jqfwb5u03hm 
       foreign key (service_id) 
       references services;

    alter table if exists services 
       add constraint FKjos7fyyy9lrfnshhvyxnlh935 
       foreign key (service_category_id) 
       references service_categories;

    alter table if exists user_addresses 
       add constraint FKn2fisxyyu3l9wlch3ve2nocgp 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists wishlists 
       add constraint FKl7ao98u2bm8nijc1rv4jobcrx 
       foreign key (product_id) 
       references products;

    alter table if exists wishlists 
       add constraint FK330pyw2el06fn5g28ypyljt16 
       foreign key (user_id) 
       references users;
