-- Harden legacy baseline replay for environments with pre-existing schema/data.
-- Keep V1 immutable and add defensive guards here.

-- 1) no_show_config: create only when missing.
CREATE TABLE IF NOT EXISTS no_show_config
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted           BOOLEAN                                 NOT NULL,
    is_active            BOOLEAN                                 NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by           VARCHAR(255),
    updated_by           VARCHAR(255),
    grace_period_minutes INTEGER                                 NOT NULL,
    auto_mark_no_show    BOOLEAN                                 NOT NULL,
    forfeit_deposit      BOOLEAN                                 NOT NULL,
    penalty_amount       DECIMAL(12, 2)                          NOT NULL,
    allow_late_checkin   BOOLEAN                                 NOT NULL,
    late_checkin_minutes INTEGER                                 NOT NULL,
    CONSTRAINT pk_no_show_config PRIMARY KEY (id)
);

-- 2) bookings date columns: avoid rename collisions when old/new columns coexist.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_start_date'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_check_in_date'
        ) THEN
            ALTER TABLE bookings DROP COLUMN IF EXISTS booking_start_date;
        ELSE
            ALTER TABLE bookings RENAME COLUMN booking_start_date TO booking_check_in_date;
        END IF;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_end_date'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_check_out_date'
        ) THEN
            ALTER TABLE bookings DROP COLUMN IF EXISTS booking_end_date;
        ELSE
            ALTER TABLE bookings RENAME COLUMN booking_end_date TO booking_check_out_date;
        END IF;
    END IF;
END $$;

-- 3) work_shift_registrations.status: tolerate legacy rows during replay.
DO $$
DECLARE c RECORD;
BEGIN
    FOR c IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'work_shift_registrations'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) ILIKE '%status%'
    LOOP
        EXECUTE format('ALTER TABLE work_shift_registrations DROP CONSTRAINT IF EXISTS %I', c.conname);
    END LOOP;
END $$;

ALTER TABLE work_shift_registrations
    ADD CONSTRAINT work_shift_registrations_status_check
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'PENDING_LEAVE', 'ON_LEAVE')) NOT VALID;
