-- V20: Add is_additional_charge to services; create booking_pet_service_items (add-on / additional charge items per booking_pet_service).

-- 1. Add is_additional_charge to services
ALTER TABLE IF EXISTS services
    ADD COLUMN IF NOT EXISTS is_additional_charge boolean NOT NULL DEFAULT false;

-- 2. Create booking_pet_service_items (intermediary: add-ons and staff-added charges per booking_pet_service)
CREATE TABLE IF NOT EXISTS booking_pet_service_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_pet_service_id bigint NOT NULL,
    parent_service_id bigint NOT NULL,
    item_service_id bigint NOT NULL,
    item_type varchar(50) NOT NULL,
    charge_reason TEXT,
    charge_evidence TEXT,
    charged_by varchar(255),
    charge_approved_by varchar(255),
    charge_approved_at timestamp(6),
    notes TEXT,
    staff_notes TEXT,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    created_by varchar(255),
    updated_by varchar(255),
    CONSTRAINT fk_bpsi_booking_pet_service FOREIGN KEY (booking_pet_service_id) REFERENCES booking_pet_services(id),
    CONSTRAINT fk_bpsi_parent_service FOREIGN KEY (parent_service_id) REFERENCES services(id),
    CONSTRAINT fk_bpsi_item_service FOREIGN KEY (item_service_id) REFERENCES services(id)
);

CREATE INDEX IF NOT EXISTS idx_bpsi_booking_pet_service_id ON booking_pet_service_items(booking_pet_service_id);
CREATE INDEX IF NOT EXISTS idx_bpsi_item_service_id ON booking_pet_service_items(item_service_id);
