-- ===== REPLIED_AT IN FEEDBACKS =====
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS replied_at TIMESTAMP;

-- ===== REFUND PROOF IN BOOKING_DEPOSITS =====
ALTER TABLE booking_deposits ADD COLUMN IF NOT EXISTS refund_proof VARCHAR(500);
