ALTER TABLE booking_pets
ADD COLUMN IF NOT EXISTS pet_type VARCHAR(100),
ADD COLUMN IF NOT EXISTS status VARCHAR(50);

ALTER TABLE booking_pet_services
ADD COLUMN IF NOT EXISTS base_price NUMERIC(12,2);
