-- === Merged from: V5__service_room_types_many_to_many.sql ===
-- N-N: Service <-> RoomType (má»™t dá»‹ch vá»¥ cÃ³ nhiá»u loáº¡i phÃ²ng, má»™t loáº¡i phÃ²ng cÃ³ thá»ƒ dÃ¹ng cho nhiá»u dá»‹ch vá»¥)
CREATE TABLE IF NOT EXISTS service_room_types (
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    room_type_id BIGINT NOT NULL REFERENCES room_types(id) ON DELETE CASCADE,
    PRIMARY KEY (service_id, room_type_id),
    CONSTRAINT uq_service_room_type UNIQUE (service_id, room_type_id)
);

CREATE INDEX IF NOT EXISTS idx_service_room_types_service_id ON service_room_types(service_id);
CREATE INDEX IF NOT EXISTS idx_service_room_types_room_type_id ON service_room_types(room_type_id);

-- Migrate existing room_types.service_id into join table safely
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns 
               WHERE table_name='room_types' AND column_name='service_id') THEN
        
        INSERT INTO service_room_types (service_id, room_type_id)
        SELECT service_id, id FROM room_types 
        WHERE service_id IS NOT NULL
        ON CONFLICT (service_id, room_type_id) DO NOTHING;

        -- Drop FK and column from room_types
        ALTER TABLE room_types DROP COLUMN service_id;
    END IF;
END $$;


-- === Merged from: V5__shift_role_config_and_registration_role_work_type.sql ===
-- Báº£ng Ä‘á»‹nh má»©c sá»‘ lÆ°á»£ng theo vai trÃ² cho tá»«ng ca (shift_id, position_id, max_slots)
create table if not exists shift_role_configs (
    config_id bigint generated by default as identity,
    work_shift_id bigint not null,
    position_id bigint not null,
    max_slots integer not null default 1,
    is_active boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (config_id),
    constraint uk_shift_role_config_shift_position unique (work_shift_id, position_id),
    constraint fk_shift_role_config_work_shift foreign key (work_shift_id) references work_shifts(shift_id),
    constraint fk_shift_role_config_position foreign key (position_id) references staff_positions(position_id)
);

-- Bá»• sung role_at_registration (position_id) vÃ  work_type cho Ä‘Äƒng kÃ½ ca
alter table work_shift_registrations
    add column if not exists position_id bigint,
    add column if not exists work_type varchar(20);

-- Chá»‰ thÃªm constraint náº¿u chÆ°a tá»“n táº¡i (DB Ä‘Ã£ Ã¡p dá»¥ng V4 cÅ© cÃ³ thá»ƒ Ä‘Ã£ cÃ³)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_registration_position'
      AND conrelid = 'public.work_shift_registrations'::regclass
  ) THEN
    ALTER TABLE work_shift_registrations
      ADD CONSTRAINT fk_registration_position
      FOREIGN KEY (position_id) REFERENCES staff_positions(position_id);
  END IF;
END $$;



