-- Bảng định mức số lượng theo vai trò cho từng ca (shift_id, position_id, max_slots)
create table if not exists shift_role_configs (
    config_id bigint generated by default as identity,
    work_shift_id bigint not null,
    position_id bigint not null,
    max_slots integer not null default 1,
    is_active boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (config_id),
    constraint uk_shift_role_config_shift_position unique (work_shift_id, position_id),
    constraint fk_shift_role_config_work_shift foreign key (work_shift_id) references work_shifts(shift_id),
    constraint fk_shift_role_config_position foreign key (position_id) references staff_positions(position_id)
);

-- Bổ sung role_at_registration (position_id) và work_type cho đăng ký ca
alter table work_shift_registrations
    add column if not exists position_id bigint,
    add column if not exists work_type varchar(20);

-- Chỉ thêm constraint nếu chưa tồn tại (DB đã áp dụng V4 cũ có thể đã có)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_registration_position'
      AND conrelid = 'public.work_shift_registrations'::regclass
  ) THEN
    ALTER TABLE work_shift_registrations
      ADD CONSTRAINT fk_registration_position
      FOREIGN KEY (position_id) REFERENCES staff_positions(position_id);
  END IF;
END $$;

