-- Bảng lưu từng lần thanh toán hóa đơn (không phải cọc). Khách có thể thanh toán nhiều lần, nhiều hình thức.
-- Khi remaining_amount của booking về 0 thì payment_status = 'PAID', payment_method lưu JSON array các hình thức.

-- 1. Đổi cột payment_method của bookings sang TEXT để lưu JSON array, ví dụ ["CASH","BANK_TRANSFER"]
ALTER TABLE bookings
    ALTER COLUMN payment_method TYPE TEXT USING (
        CASE
            WHEN payment_method IS NULL OR payment_method = '' THEN NULL
            ELSE json_build_array(payment_method)::TEXT
        END
    );

COMMENT ON COLUMN bookings.payment_method IS 'JSON array of payment methods used for this booking, e.g. ["CASH","BANK_TRANSFER"]';

-- 2. Bảng giao dịch thanh toán từng lần
CREATE TABLE IF NOT EXISTS booking_payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    transaction_type VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    transaction_reference VARCHAR(100),
    paid_by UUID,
    paid_by_name VARCHAR(100),
    paid_at TIMESTAMP(6) NOT NULL,
    received_by UUID,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_bpt_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_bpt_paid_by FOREIGN KEY (paid_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_bpt_received_by FOREIGN KEY (received_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_bpt_transaction_type CHECK (transaction_type IN ('FINAL_PAYMENT')),
    CONSTRAINT chk_bpt_payment_method CHECK (payment_method IN ('CASH', 'BANK_TRANSFER', 'VIETQR')),
    CONSTRAINT chk_bpt_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_bpt_booking_id ON booking_payment_transactions(booking_id);
CREATE INDEX IF NOT EXISTS idx_bpt_paid_at ON booking_payment_transactions(paid_at);
CREATE INDEX IF NOT EXISTS idx_bpt_status ON booking_payment_transactions(status);

COMMENT ON TABLE booking_payment_transactions IS 'Từng lần thanh toán hóa đơn (phần còn lại), không bao gồm thanh toán cọc';
COMMENT ON COLUMN booking_payment_transactions.transaction_type IS 'FINAL_PAYMENT = thanh toán phần còn lại';
COMMENT ON COLUMN booking_payment_transactions.amount IS 'Số tiền giao dịch này';
COMMENT ON COLUMN booking_payment_transactions.transaction_reference IS 'Mã giao dịch từ ngân hàng, VietQR...';
COMMENT ON COLUMN booking_payment_transactions.paid_by IS 'FK users - khách hàng nào trả (nếu có nhiều người)';
COMMENT ON COLUMN booking_payment_transactions.paid_by_name IS 'Tên người trả (nhập tay, có thể fill từ customer_name của booking)';
COMMENT ON COLUMN booking_payment_transactions.paid_at IS 'Thời điểm thanh toán';
COMMENT ON COLUMN booking_payment_transactions.received_by IS 'FK users (admin) - nhân viên xác nhận thu';
COMMENT ON COLUMN booking_payment_transactions.status IS 'PENDING=Chờ xác nhận, COMPLETED=Đã xác nhận, FAILED=Thất bại, CANCELLED=Đã hủy';
