-- Đảm bảo bảng newsletter_subscriptions tồn tại (trường hợp DB thiếu bảng do Flyway chưa chạy V57 hoặc restore backup)
CREATE TABLE IF NOT EXISTS newsletter_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE newsletter_subscriptions IS 'Đăng ký nhận newsletter';
