-- === Merged from: V8__ensure_staff_fixed_schedules_table.sql ===
-- V18: Ensure staff_fixed_schedules table exists (idempotent).
-- Some environments may have Flyway history but missing table; this migration recreates it safely.

CREATE TABLE IF NOT EXISTS staff_fixed_schedules (
    schedule_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id      BIGINT NOT NULL,
    position_id   BIGINT NOT NULL,
    day_of_week   INTEGER NOT NULL,
    is_afternoon  BOOLEAN NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255)
);

-- Unique constraint (ignore if already exists)
DO $$
BEGIN
    ALTER TABLE staff_fixed_schedules
        ADD CONSTRAINT uk_staff_fixed_schedule_staff_position_day_slot
            UNIQUE (staff_id, position_id, day_of_week, is_afternoon);
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN NULL;
END $$;

-- Foreign keys (ignore if already exist)
DO $$
BEGIN
    ALTER TABLE staff_fixed_schedules
        ADD CONSTRAINT fk_staff_fixed_schedule_staff
            FOREIGN KEY (staff_id) REFERENCES staff_profiles(staff_id);
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE staff_fixed_schedules
        ADD CONSTRAINT fk_staff_fixed_schedule_position
            FOREIGN KEY (position_id) REFERENCES staff_positions(position_id);
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN NULL;
END $$;



-- === Merged from: V8__staff_fixed_schedules.sql ===
-- Lá»‹ch cá»‘ Ä‘á»‹nh cá»§a nhÃ¢n viÃªn Full-time (thá»© + sÃ¡ng/chiá»u + vai trÃ²) â€“ dÃ¹ng Ä‘á»ƒ auto-fill khi táº¡o ca
create table if not exists staff_fixed_schedules (
    schedule_id bigint generated by default as identity,
    staff_id bigint not null,
    position_id bigint not null,
    day_of_week integer not null,
    is_afternoon boolean not null,
    is_active boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (schedule_id),
    constraint uk_staff_fixed_schedule_staff_position_day_slot unique (staff_id, position_id, day_of_week, is_afternoon),
    constraint fk_staff_fixed_schedule_staff foreign key (staff_id) references staff_profiles(staff_id),
    constraint fk_staff_fixed_schedule_position foreign key (position_id) references staff_positions(position_id)
);


