-- Lịch cố định của nhân viên Full-time (thứ + sáng/chiều + vai trò) – dùng để auto-fill khi tạo ca
create table if not exists staff_fixed_schedules (
    schedule_id bigint generated by default as identity,
    staff_id bigint not null,
    position_id bigint not null,
    day_of_week integer not null,
    is_afternoon boolean not null,
    is_active boolean not null default true,
    is_deleted boolean not null default false,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (schedule_id),
    constraint uk_staff_fixed_schedule_staff_position_day_slot unique (staff_id, position_id, day_of_week, is_afternoon),
    constraint fk_staff_fixed_schedule_staff foreign key (staff_id) references staff_profiles(staff_id),
    constraint fk_staff_fixed_schedule_position foreign key (position_id) references staff_positions(position_id)
);
