-- === Merged from: V20260321143000__booking_refund_admin_evidence_evidence_url_text.sql ===
-- Created: 2026-03-21 | booking refund admin evidence: support long data URLs (base64)
-- Fixes: value too long for type character varying(255)

ALTER TABLE booking_refund_admin_evidence
    ALTER COLUMN evidence_url TYPE TEXT;


-- === Merged from: V20260321190500__harden_legacy_baseline_replay.sql ===
-- Harden legacy baseline replay for environments with pre-existing schema/data.
-- Keep V1 immutable and add defensive guards here.

-- 1) no_show_config: create only when missing.
CREATE TABLE IF NOT EXISTS no_show_config
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted           BOOLEAN                                 NOT NULL,
    is_active            BOOLEAN                                 NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by           VARCHAR(255),
    updated_by           VARCHAR(255),
    grace_period_minutes INTEGER                                 NOT NULL,
    auto_mark_no_show    BOOLEAN                                 NOT NULL,
    forfeit_deposit      BOOLEAN                                 NOT NULL,
    penalty_amount       DECIMAL(12, 2)                          NOT NULL,
    allow_late_checkin   BOOLEAN                                 NOT NULL,
    late_checkin_minutes INTEGER                                 NOT NULL,
    CONSTRAINT pk_no_show_config PRIMARY KEY (id)
);

-- 2) bookings date columns: avoid rename collisions when old/new columns coexist.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_start_date'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_check_in_date'
        ) THEN
            ALTER TABLE bookings DROP COLUMN IF EXISTS booking_start_date;
        ELSE
            ALTER TABLE bookings RENAME COLUMN booking_start_date TO booking_check_in_date;
        END IF;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_end_date'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_check_out_date'
        ) THEN
            ALTER TABLE bookings DROP COLUMN IF EXISTS booking_end_date;
        ELSE
            ALTER TABLE bookings RENAME COLUMN booking_end_date TO booking_check_out_date;
        END IF;
    END IF;
END $$;

-- 3) work_shift_registrations.status: tolerate legacy rows during replay.
DO $$
DECLARE c RECORD;
BEGIN
    FOR c IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'work_shift_registrations'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) ILIKE '%status%'
    LOOP
        EXECUTE format('ALTER TABLE work_shift_registrations DROP CONSTRAINT IF EXISTS %I', c.conname);
    END LOOP;
END $$;

ALTER TABLE work_shift_registrations
    ADD CONSTRAINT work_shift_registrations_status_check
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'PENDING_LEAVE', 'ON_LEAVE')) NOT VALID;


-- === Merged from: V20260322120000__booking_pet_service_staff_many_to_many.sql ===
-- N-N: booking_pet_service <-> staff_profiles; thay assigned_staff_id.

CREATE TABLE IF NOT EXISTS booking_pet_service_staff (
    booking_pet_service_id BIGINT NOT NULL REFERENCES booking_pet_services(id) ON DELETE CASCADE,
    staff_id BIGINT NOT NULL REFERENCES staff_profiles(staff_id) ON DELETE CASCADE,
    CONSTRAINT pk_booking_pet_service_staff PRIMARY KEY (booking_pet_service_id, staff_id)
);

CREATE INDEX IF NOT EXISTS idx_bps_staff_staff_id ON booking_pet_service_staff(staff_id);

INSERT INTO booking_pet_service_staff (booking_pet_service_id, staff_id)
SELECT id, assigned_staff_id
FROM booking_pet_services
WHERE assigned_staff_id IS NOT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE booking_pet_services DROP COLUMN IF EXISTS assigned_staff_id;


-- === Merged from: V20260325140000__add_customer_review_photos_to_booking_pet_services.sql ===
-- Add customer_review_photos column to booking_pet_services table
-- This column stores comma-separated URLs of photos uploaded by customers during review.

ALTER TABLE booking_pet_services ADD COLUMN customer_review_photos TEXT;


-- === Merged from: V20260325150000__bump_payment_order_code_sequence.sql ===
-- Restart payment_order_code_seq at 5000000 to avoid collisions with previous PayOS transactions in local environments
ALTER SEQUENCE payment_order_code_seq RESTART WITH 5000000;


-- === Merged from: V20260328120000__credential_reissue_history.sql ===
-- Created: 2026-03-28 | staff password reissue audit + admin approval tokens
CREATE TABLE credential_reissue_history (
    id UUID PRIMARY KEY,
    subject_user_id UUID NOT NULL REFERENCES users (id),
    subject_role_name VARCHAR(50) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    admin_action_token_hash VARCHAR(128),
    expires_at TIMESTAMP(6),
    resolved_at TIMESTAMP(6),
    resolved_by_user_id UUID REFERENCES users (id),
    correlation_id UUID NOT NULL,
    metadata TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_credential_reissue_subject_status ON credential_reissue_history (subject_user_id, status);
CREATE INDEX idx_credential_reissue_token_hash ON credential_reissue_history (admin_action_token_hash);


