export const APP_SETTING_KEYS = {
    SHOP_ADDRESS: 'SHOP_ADDRESS',
    SHOP_LAT: 'SHOP_LAT',
    SHOP_LNG: 'SHOP_LNG',
    SHOP_PHONE: 'SHOP_PHONE',
    SHOP_EMAIL: 'SHOP_EMAIL',
    SOCIAL_FACEBOOK: 'SOCIAL_FACEBOOK',
    SOCIAL_INSTAGRAM: 'SOCIAL_INSTAGRAM',
    SOCIAL_APPLE_STORE: 'SOCIAL_APPLE_STORE',
    SOCIAL_PLAY_STORE: 'SOCIAL_PLAY_STORE',
    SHOP_WEBSITE: 'SHOP_WEBSITE',
} as const;
