export const PROVINCES = [
    { id: 1, name: "TP. Hà Nội" },
    { id: 4, name: "Tỉnh Cao Bằng" },
    { id: 8, name: "Tỉnh Tuyên Quang" },
    { id: 11, name: "Tỉnh Điện Biên" },
    { id: 12, name: "Tỉnh Lai Châu" },
    { id: 14, name: "Tỉnh Sơn La" },
    { id: 15, name: "Tỉnh Lào Cai" },
    { id: 19, name: "Tỉnh Thái Nguyên" },
    { id: 20, name: "Tỉnh Lạng Sơn" },
    { id: 22, name: "Tỉnh Quảng Ninh" },
    { id: 24, name: "Tỉnh Bắc Ninh" },
    { id: 25, name: "Tỉnh Phú Thọ" },
    { id: 31, name: "TP. Hải Phòng" },
    { id: 33, name: "Tỉnh Hưng Yên" },
    { id: 37, name: "Tỉnh Ninh Bình" },
    { id: 38, name: "Tỉnh Thanh Hóa" },
    { id: 40, name: "Tỉnh Nghệ An" },
    { id: 42, name: "Tỉnh Hà Tĩnh" },
    { id: 44, name: "Tỉnh Quảng Trị" },
    { id: 46, name: "TP. Huế" },
    { id: 48, name: "TP. Đà Nẵng" },
    { id: 51, name: "Tỉnh Quảng Ngãi" },
    { id: 52, name: "Tỉnh Gia Lai" },
    { id: 56, name: "Tỉnh Khánh Hòa" },
    { id: 66, name: "Tỉnh Đắk Lắk" },
    { id: 68, name: "Tỉnh Lâm Đồng" },
    { id: 75, name: "Tỉnh Đồng Nai" },
    { id: 79, name: "TP. Hồ Chí Minh" },
    { id: 80, name: "Tỉnh Tây Ninh" },
    { id: 82, name: "Tỉnh Đồng Tháp" },
    { id: 86, name: "Tỉnh Vĩnh Long" },
    { id: 91, name: "Tỉnh An Giang" },
    { id: 92, name: "TP. Cần Thơ" },
    { id: 96, name: "Tỉnh Cà Mau" },
    { id: 0, name: "Khác" }
];
