spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROD}
    username: ${SPRING_DATASOURCE_USERNAME_PROD}
    password: ${SPRING_DATASOURCE_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect # Let Hibernate auto-detect for Neon (Postgres 17+)
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
          batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    out-of-order: true

  sql:
    init:
      mode: never

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI_PROD}
    
    redis:
      url: ${SPRING_DATA_REDIS_URL_PROD:redis://localhost:6379}
      timeout: 2000ms
  

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS_PROD:http://localhost:9200}
    connection-timeout: ${SPRING_ELASTICSEARCH_CONNECTION_TIMEOUT_PROD:5s}
    socket-timeout: ${SPRING_ELASTICSEARCH_SOCKET_TIMEOUT_PROD:60s}

# Logging for production
logging:
  level:
    root: INFO
    fpt.teddypet: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
